commons: &commons
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeouts: 5000


sqlite:
  <<: *commons
  adapter: sqlite3
  database: ---

mysql_or_mariadb:
  <<: *commons
  adapter: mysql2
  host: ---
  port: ---
  username: ---
  password: ---
  database: ---

postgres:
  <<: *commons
  adapter: postgresql
  host: ---
  port: ---
  username: ---
  password: ---
  database: ---

sql_server:
  <<: *commons
  adapter: sqlserver
  host: ---
  port: ---
  username: ---
  password: ---
  database: ---
  subschema: dbo
